apiVersion: v1
kind: Service
metadata:
  name: board-app
  namespace: board-app
  labels:
    app: board-app
spec:
  selector:
    app: board-app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
